name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --headless https://radar.cloudflare.com/charts/VerifiedBotsTableCard/fetch
